AWS_ACCESS_KEY_ID: AKIAIRFN75C76MSESPKA
AWS_SECRET_ACCESS_KEY: 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
S3_BUCKET_NAME: campusnow-images
AWS_REGION: us-east-1


TWILLIO_ACCOUNT: AC183733e815b7d13e3a011771f0ff69d9
TWILLIO_SECRET: 3303df01b99d28f938dd0e2321394cfa
TWILLIO_NUMBER: 7812096211
