development:
  adapter: postgresql
  encoding: utf8
  database: project_development_campusNow
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test_campusNow
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production_campusNow
  pool: 5
  username:
  password:
